# Generated by Django 6.0 on 2025-12-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PR', 'Programming'), ('LE', 'Literature'), ('GE', 'Geography')], max_length=200)),
                ('payment', models.CharField(choices=[('CC', 'credit card'), ('CA', 'cash')], max_length=2)),
            ],
        ),
    ]
