# Generated by Django 5.2.9 on 2025-12-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_course_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('AC', 'active'), ('CO', 'completed'), ('DR', 'dropped'), ('NW', 'new')], default='NW', max_length=2),
        ),
    ]
