# Generated by Django 5.2.9 on 2025-12-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
